name: Deploy Android

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch to build from
        default: master

jobs:
  build_android:
    name: Build Android Production
    type: build
    environment: production
    params:
      platform: android
      profile: production

  notify_success:
    name: Share Android Production Link
    needs: [build_android]
    if: ${{ success() }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_SUCCESS }}
          message: |
            Android production build is ready.

            App: ${{ needs.build_android.outputs.app_identifier }}
            Version: ${{ needs.build_android.outputs.app_version }}
            Build number: ${{ needs.build_android.outputs.app_build_version }}
            Build link: https://expo.dev/builds/${{ needs.build_android.outputs.build_id }}

  notify_failure:
    name: Notify Android Production Failure
    after: [build_android]
    if: ${{ failure() }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_FAILURE }}
          message: |
            Android production build failed.

            Workflow: ${{ workflow.name }}
            Details: ${{ workflow.url }}
