name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch to build from
        default: master

jobs:
  build_android:
    name: Build Android Production
    type: build
    environment: production
    params:
      platform: android
      profile: production

  build_ios:
    name: Build iOS Production
    type: build
    environment: production
    params:
      platform: ios
      profile: production

  notify_success:
    name: Share Production Build Links
    needs: [build_android, build_ios]
    if: ${{ success() }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_SUCCESS }}
          message: |
            Production builds are ready.

            Android version: ${{ needs.build_android.outputs.app_version }}
            Android build link: https://expo.dev/builds/${{ needs.build_android.outputs.build_id }}

            iOS version: ${{ needs.build_ios.outputs.app_version }}
            iOS build link: https://expo.dev/builds/${{ needs.build_ios.outputs.build_id }}

  notify_failure:
    name: Notify Production Build Failure
    after: [build_android, build_ios]
    if: ${{ failure() }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_FAILURE }}
          message: |
            Production build failed.

            Workflow: ${{ workflow.name }}
            Details: ${{ workflow.url }}
