name: Deploy Android

on:
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android Production
    type: build
    environment: production
    params:
      platform: android
      profile: production

  notify_slack_success:
    name: Notify Slack (Success)
    after: [build_android]
    environment: production
    if: ${{ after.build_android.status == 'finished' }}
    steps:
      - uses: eas/send_slack_message
        with:
          message: |
            Android production build succeeded.
            Workflow: ${{ workflow.name }}
            Version: ${{ after.build_android.outputs.app_version }}
            Build status: ${{ after.build_android.status }}
            Build URL: https://expo.dev/builds/${{ after.build_android.outputs.build_id }}
            Workflow URL: ${{ workflow.url }}
          url: ${{ env.SLACK_HOOK_URL_SUCCESS }}

  notify_slack_failure:
    name: Notify Slack (Failure)
    after: [build_android]
    environment: production
    if: ${{ after.build_android.status != 'finished' }}
    steps:
      - uses: eas/send_slack_message
        with:
          message: |
            Android production build failed.
            Workflow: ${{ workflow.name }}
            Build status: ${{ after.build_android.status }}
            Build URL: https://expo.dev/builds/${{ after.build_android.outputs.build_id }}
            Workflow URL: ${{ workflow.url }}
          url: ${{ env.SLACK_HOOK_URL_FAILURE }}
