name: Deploy

"on":
  workflow_dispatch: {}
  push:
    branches:
      - release
    paths:
      - mobile/**

jobs:
  build_android:
    name: Build Android
    type: build
    environment: production
    params:
      platform: android
      profile: production

  build_ios:
    name: Build iOS
    type: build
    environment: production
    params:
      platform: ios
      profile: production

  submit_ios:
    name: Submit iOS
    needs: [build_ios]
    type: submit
    environment: production
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production

  notify_android_success:
    name: Notify Android Success
    needs: [build_android]
    if: ${{ needs.build_android.result == 'success' }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_SUCCESS }}
          message: |
            Android production build is ready.

            App: ${{ needs.build_android.outputs.app_identifier }}
            Version: ${{ needs.build_android.outputs.app_version }}
            Build number: ${{ needs.build_android.outputs.app_build_version }}
            Build link: https://expo.dev/builds/${{ needs.build_android.outputs.build_id }}

  notify_android_failure:
    name: Notify Android Failure
    needs: [build_android]
    if: ${{ needs.build_android.result == 'failure' }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_FAILURE }}
          message: |
            Android production build failed.

            Workflow: ${{ workflow.name }}
            Details: ${{ workflow.url }}

  notify_ios_success:
    name: Notify iOS Success
    needs: [build_ios, submit_ios]
    if: ${{ needs.build_ios.result == 'success' && needs.submit_ios.result == 'success' }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_SUCCESS }}
          message: |
            iOS production build submitted to App Store.

            App: ${{ needs.build_ios.outputs.app_identifier }}
            Version: ${{ needs.build_ios.outputs.app_version }}
            Build number: ${{ needs.build_ios.outputs.app_build_version }}
            Build link: https://expo.dev/builds/${{ needs.build_ios.outputs.build_id }}

  notify_ios_failure:
    name: Notify iOS Failure
    needs: [build_ios, submit_ios]
    if: ${{ needs.build_ios.result == 'failure' || needs.submit_ios.result == 'failure' }}
    environment: production
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_FAILURE }}
          message: |
            iOS production deployment failed.

            Workflow: ${{ workflow.name }}
            Details: ${{ workflow.url }}
