name: Android Preview Build

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch to build from
        default: master

jobs:
  build_android_preview:
    name: Build Android Preview
    type: build
    environment: preview
    params:
      platform: android
      profile: preview

  notify_slack_success:
    name: Notify Slack (Success)
    after: [build_android_preview]
    environment: preview
    if: ${{ after.build_android_preview.status == 'finished' }}
    steps:
      - uses: eas/send_slack_message
        with:
          message: |
            Android preview build succeeded.
            Workflow: ${{ workflow.name }}
            Branch: ${{ inputs.branch }}
            Build status: ${{ after.build_android_preview.status }}
            App: ${{ after.build_android_preview.outputs.app_identifier }}
            Version: ${{ after.build_android_preview.outputs.app_version }}
            Build URL: https://expo.dev/builds/${{ after.build_android_preview.outputs.build_id }}
            Workflow URL: ${{ workflow.url }}
          url: ${{ env.SLACK_HOOK_URL_SUCCESS }}

  notify_slack_failure:
    name: Notify Slack (Failure)
    after: [build_android_preview]
    environment: preview
    if: ${{ after.build_android_preview.status != 'finished' }}
    steps:
      - uses: eas/send_slack_message
        with:
          message: |
            Android preview build failed.
            Workflow: ${{ workflow.name }}
            Branch: ${{ inputs.branch }}
            Build status: ${{ after.build_android_preview.status }}
            Workflow URL: ${{ workflow.url }}
          url: ${{ env.SLACK_HOOK_URL_FAILURE }}
