name: Android Preview Build

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch to build from
        default: master

jobs:
  build_android_preview:
    name: Build Android Preview
    type: build
    environment: preview
    params:
      platform: android
      profile: preview

  notify_success:
    name: Share Android Preview Link
    needs: [build_android_preview]
    if: ${{ success() }}
    environment: preview
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_SUCCESS }}
          message: |
            Android preview build is ready.

            App: ${{ needs.build_android_preview.outputs.app_identifier }}
            Version: ${{ needs.build_android_preview.outputs.app_version }}
            Build number: ${{ needs.build_android_preview.outputs.app_build_version }}
            Build link: https://expo.dev/builds/${{ needs.build_android_preview.outputs.build_id }}

  notify_failure:
    name: Notify Android Preview Failure
    after: [build_android_preview]
    if: ${{ failure() }}
    environment: preview
    steps:
      - uses: eas/send_slack_message
        with:
          slack_hook_url: ${{ env.SLACK_HOOK_URL_FAILURE }}
          message: |
            Android preview build failed.

            Workflow: ${{ workflow.name }}
            Details: ${{ workflow.url }}
